version: 2

release:
  draft: true

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin

signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args:
      - "sign-blob"
      - "--oidc-issuer=https://token.actions.githubusercontent.com"
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum

brews:
  - name: ecsv
    repository:
      owner: dhth
      name: homebrew-tap
    directory: Formula
    license: MIT
    homepage: "https://github.com/dhth/ecsv"
    description: "Quickly check the versions of your systems running in ECS tasks across various environments"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
